### ISSUE TITLE
IMPORT: Validation

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#171]
**ACCEPTANCE CRITERIA**
When I upload the CSV validation these, things need to be present:
- [x] A title 
- [x] A primary file

**Comment by no-reply** [comment]
This is no longer blocked.

**Comment by no-reply** [comment]
I put up an example implementation of the title validation at https://github.com/curationexperts/mahonia/tree/import-validation-test

This is untested, and also has the downside that it runs through the `ImportRecord` instead of parsing directly out of the CSV, which may be better overall. I'm leaning toward using the OOB validator, unless you (@jenlindner) have strong opinions.
