### ISSUE TITLE
METADATA: data type for the "EDTF Date" field is EDTF

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#186]
**ACCEPTANCE**
 - [ ] The date field (:RDF::Vocab::DC11.date) used the ~Europeana~ Extended Date Time Format (EDTF) as it's data type
- [x] The field should have the label "EDTF Date" 

**REFERENCE**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by mark-dce** [comment]
WIP at https://github.com/curationexperts/mahonia/tree/date-edtf

**Comment by mark-dce** [comment]
**ISSUE**
The `EDTF Date` field on the show view appears to be showing the value of the `Date Label` field instead of the EDTF Date.  There seems to be similar behavior on the edit form.

**ACCEPTANCE**
- [ ] The `EDTF Date` field saves and displays independently of the `Date Label1 field
- [ ] The `EDTF Date` field appears with proper type information in the Turtle view with the predicate `   <http://purl.org/dc/elements/1.1/date>
- [ ] The `Date Label` field appears as a string in the Turtle view with the predicate `<http://rs.tdwg.org/dwc/terms/verbatimEventDate>`

**Comment by mark-dce** [comment]
FWIW - it looks like the predicate for `EDTF Date` was changed incorrectly in this PR https://github.com/curationexperts/mahonia/commit/8598f9ef71bace7275dc66f65c60cba212f7b208.  The predicate for the `date` attribute should have remained DC11.date - it's a separate thing from the label for the date.
