### ISSUE TITLE
Confirm whether additional BePress terms need to be migrated

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/mahonia#192]
The following terms exist in BEPress exports, but are not currently included in the Mahonia metadata model. Do they need to be migrated?

https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=1201290981

**ACCEPTANCE CRITERIA**
 - [x] OSHU has confirmed either 1) no additional BePress terms need to be migrated or 2) which ones do, and what their approximately-matched Hyrax terms should be

**Comment by shanitajohn** [comment]
**Note from Thornhik in Mahonia Slack Channel, 12/19/17**
Data mapping is all set.  If you are wondering, OHSU does not want to import  all the Bepress data fields because some are not used cataloging. They are just blank and irrelevant to our current processes. Let me know if you have any questions. https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit?usp=sharing
